export const TOGGLE_VISIBILITY = 'NEW_APPOINTMENT/TOGGLE_VISIBILITY';
export const SET_DATE_TIME = 'NEW_APPOINTMENT/SET_DATE_TIME';
export const SET_SERVICES = 'NEW_APPOINTMENT/SET_SERVICES';
export const ALL_SERVICES = 'NEW_APPOINTMENT/All_SERVICES';
