export const SET_DATE_FILTER = 'APPOINTMENT/SET_DATE_FILTER';
export const SET_VISIBILITY_FILTER = 'APPOINTMENT/SET_VISIBILITY_FILTER';
export const SET_NEXT_APPOINTMENT = 'APPOINTMENT/SET_NEXT_APPOINTMENT';
export const SET_LAST_APPOINTMENT = 'APPOINTMENT/SET_LAST_APPOINTMENT';
